### ISSUE TITLE
Impossible to work with c9, caused by empty code editor holder 

### ISSUE THREAD

**Issue by SylannBin** [c9/core#394] opened 2017-02-16 23:29 UTC
## Explanation

I am facing a terrible problem that has made me incapable of working on a specific shared project with my specific account.
The project is still usable with other accounts, and I can work on other projects with my account.

![image](https://cloud.githubusercontent.com/assets/17208592/23046186/7195a3b6-f4a8-11e6-89d6-324ac05b9f48.png)

I have tried the following:

- Log out and in
- Clean some browser's data
- Work on a different browser
- Restart the c9 project
- Change between different display modes
- switched full IDE, sublime etc...
- And a lot of option and settings modifications
... without having anything changed

## How it happend:

The editor was split vertically when I closed the tab (page).
When I came back, the code editor holder was split in two : a black rectangle on the left and the vertically split code editor on the right (doubly split so to say).
I decided to refresh the page to solve what I thought as a simple bug.
After the page was loaded again, the whole code editor holder was now black and it has been impossible to open a file, the settings, or anything that should open in there.

In the chrome console, I once found an error mentionning currentSession.getStatus is not a function.

When loading the page the following errors happen:
```
GET ****/workspace/.c9/test.settings.yml?access_token=**** 404 (Not Found)

GET ****home/.c9/installed?access_token=**** 404 (Not Found)

PATCH https://api.c9.io/projects/****/?access_token=**** 403 (Forbidden)
```

Now, this one happens when I try to open the settings:

```
Uncaught Error: Called open too early. Please wait until a pane is available. Use the ready event.
    at createTab (workspace-nodejs.js:43250)
    at Plugin.open (workspace-nodejs.js:43365)
    at Object.exec (workspace-nodejs.js:15007)
    at workspace-nodejs.js:5652
    at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (workspace-nodejs.js:4236)
    at Plugin.exec (workspace-nodejs.js:42566)
    at apf.button.value.onclick (workspace-nodejs.js:38965)
    at apf.button.dispatchEvent (workspace-nodejs.js:33447)
    at HTMLDivElement.$ext.onmouseup (workspace-nodejs.js:35957)
```

This happens when I try to open a file:

```
Uncaught Error: Called open too early. Please wait until a pane is available. Use the ready event.
    at createTab (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:43250:42)
    at Plugin.open (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:43365:5)
    at https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:21250:67
    at Array.forEach (native)
    at Array.openSelection (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:21249:5)
    at Tree.EventEmitter._emit.EventEmitter._dispatchEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:4236:46)
    at MouseHandler.onClick (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5308:74)
    at Tree.EventEmitter._emit.EventEmitter._dispatchEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:4236:126)
    at MouseHandler.onMouseEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5452:13)
    at MouseHandler.onMouseUp (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5306:43)
```

I hope it helps to track this issue because right now, I can't work anymore with my account.
This is not a little bug.

**Comment by nightwing** [comment] 2017-02-17 06:23
you can open the workspace with ?reset=state to reset state config.

But before doing that please open the workspace with ?config=1
and run the following code snippet in chrome devtools.
and give text from clipboard to me
```js
copy(JSON.parse(document.body.textContent).architectConfig.filter(function(x) {
    return /settings/.test(x.packagePath)
})[0].settings.state)
 ```
That will allow us to find the root cause of the issue.

**Comment by SylannBin** [comment] 2017-02-17 11:46
?reset=state worked as expected. Much thanks!

More via mail.

**Comment by nightwing** [comment] 2017-02-20 09:18
fixed by https://github.com/c9/core/commit/0841961fc7f43bca7bd360fdc7a69caef7de2fe2

**Closed by nightwing** 2017-02-20 09:18 UTC
