### ISSUE TITLE
New tree context menu items indexes not honored

### ISSUE THREAD

**Issue by thegecko** [c9/core#139] opened 2015-08-30 18:27 UTC
When you add context menu items to the tree context menu, not all of the items end up in the right places.

To recreate this, create a new custom workspace on c9.io and add a new full plugin.

Add some tree context menu items (observing the correct imports of course) in the load function:

            tree.getElement("mnuCtxTree", function(mnuCtxTree) {
                ui.insertByIndex(mnuCtxTree, new ui.item({
                    caption: "item one"
                }), 100, plugin);
                ui.insertByIndex(mnuCtxTree, new ui.item({
                    caption: "item two"
                }), 110, plugin);
            });

I would expect both items to appear in the menu near the top, but item one appears at the bottom.

**Comment by nightwing** [comment] 2015-08-30 21:44
I couldn't reproduce the issue with `item one` appearing at the bottom.
`item one` either appears before or after the first item of the menu because index of the first item is `100` as well. Using indexes smaller than `100` makes both items appear at the very top.

**Comment by thegecko** [comment] 2015-08-31 13:08
Strange, I just recreated this following the instructions above.

To be more explicit...
Using Chrome on Mac, create a new custom workspace on c9.io.
Add a new full plugin and add the tree import:

```var tree = imports.tree;```

Add the menu items to the load function so it reads:

```
        function load() {
            commands.addCommand({
                name: "mycommand",
                bindKey: { mac: "Command-I", win: "Ctrl-I" },
                isAvailable: function(){ return true; },
                exec: function() {
                    showing ? hide() : show();
                }
            }, plugin);
            
            menus.addItemByPath("Tools/My Menu Item", new ui.item({
                command: "mycommand"
            }), 300, plugin);
            
            settings.on("read", function(e){
                settings.setDefaults("user/my-plugin", [
                    ["first", "1"],
                    ["second", "all"]
                ]);
            });
            
            tree.getElement("mnuCtxTree", function(mnuCtxTree) {
                ui.insertByIndex(mnuCtxTree, new ui.item({
                    caption: "item one"
                }), 100, plugin);
                ui.insertByIndex(mnuCtxTree, new ui.item({
                    caption: "item two"
                }), 110, plugin);
            });
        
            prefs.add({
            ...
```

Save the file and start in debug mode.

<img width="706" alt="screen shot 2015-08-31 at 14 05 10" src="https://cloud.githubusercontent.com/assets/61341/9579331/b33c4b4a-4fe9-11e5-80cf-77b9367af31f.png">

**Comment by nightwing** [comment] 2015-09-02 01:31
Thanks for the datailed description, it helped me to find the bug.
Fixed by https://github.com/c9/core/commit/f0b760b2c44656550e45abe522925c992bc81232

**Closed by nightwing** 2015-09-02 01:31 UTC

**Comment by thegecko** [comment] 2015-09-02 09:05
Awesome!
