### ISSUE TITLE
install.sh ncurses fails on ARM ubuntu

### ISSUE THREAD

**Issue by fnoop** [c9/core#276] opened 2016-03-24 22:15 UTC
I get the same error compiling ncurses on both odroid xu4 ubuntu 15.10 and on beaglebone ubuntu 16.04:

```
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -DNDEBUG -I. -I../include -I/srv/maverick/.c9/local/include/ncurses -O2 --param max-inline-insns-single=1200 -P -c ../ncurses/lib_gen.c -o ../objects/lib_gen.o
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_27472.c:835:15: error: expected ‘)’ before ‘int’
../include/curses.h:1594:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:785: recipe for target '../objects/lib_gen.o' failed
make: *** [../objects/lib_gen.o] Error 1
```

The fix is to add -P to preprocessor, so change install.sh to:
```
echo ":Configuring Ncurses"
CPPFLAGS=-P ./configure --prefix="$C9_DIR/local" --without-tests --without-cxx
```

**Comment by justin8** [comment] 2016-03-30 01:03
Thanks for that. I'll merge this in upstream. It does fix the issue on newer GCC versions which I think was the cause here and not so much the architecture.

FYI, if you have a system version of ncurses installed via apt-get/etc it will use that instead of compiling it.

**Comment by fnoop** [comment] 2016-03-30 12:14
@justin8 could you please point to the logic that checks for ncurses?  I can't see it in the install scripts.

**Comment by justin8** [comment] 2016-03-30 23:55
Sure. I was a little wrong; you need a system installed version of tmux not ncurses. ncurses is built only if a version of tmux isn't found:

https://github.com/c9/install/blob/master/install.sh#L330

**Comment by fnoop** [comment] 2016-03-31 10:23
@justin8 Ah yes, thanks very much, saves a lot of time on slow embedded systems :)

**Comment by justin8** [comment] 2016-04-01 00:25
Thanks for finding the -P flag on that build; I had troubles with it on my rpi2 the other week as well but hadn't had the time to debug it yet.

**Comment by nightwing** [comment] 2016-04-09 22:03
fixed in https://github.com/c9/install/commit/c28c783d25cf0715cae04b3dfcc5bea74f04a2a7#diff-3fbb47e318cd8802bd325e7da9aaabe8

**Closed by nightwing** 2016-04-09 22:03 UTC
